--JOB_INFO 테이블 생성
CREATE TABLE JOB_INFO(
     JOB_ID     VARCHAR2(10),   --직업 ID
     MIN_SALARY NUMBER,         --최저급여
     MAX_SALARY NUMBER          --최고급여
);

INSERT INTO JOB_INFO VALUES ('AD_PRES', 20000, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES ('FI_MGR', 8000, 16000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 4000, 9000);
INSERT INTO JOB_INFO VALUES ('AC_MGR', 8000, 16000);
INSERT INTO JOB_INFO VALUES ('AC_ACCOUNT', 4000, 9000);
COMMIT;

SELECT * FROM JOB_INFO;

--최저급여 및 최고금액의 평균 출력
SELECT ROUND (AVG(MIN_SALARY), -1) 최저급여평균,
       ROUND (AVG(MAX_SALARY), -1) 최고급여평균
FROM JOB_INFO;

--최저 급여가 5000$ 이상인 직업 ID 출력
/* 실행순서
    1. FROM
    2. SELECT
    3. WHERE
    4. ORDER
*/
SELECT JOB_ID, MIN_SALARY MIN_SAL
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;

--최저 급여가 5000$ 이상인 정보를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS  SELECT *
    FROM JOB_INFO
    WHERE MIN_SALARY >= 5000;

SELECT * FROM V_JOB_INFO;

--최고 급여와 최저 급여의 차가 10000$ 이상인 직업 ID 개수를 출력
SELECT COUNT(*)
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= -10000;

--직업 ID명이 F1로 시작하는 자료 검색
SELECT JOB_ID
FROM V_JOB_INFO
WHERE JOB_ID LIKE 'FI%';

--MAX_SALARY가 가장 높은 직원 ID 출력
SELECT JOB_ID   
FROM V_JOB_INFO
WHERE MAX_SALARY = (SELECT MAX(MAX_SALARY) FROM V_JOB_INFO); 

